### ISSUE TITLE
Endpoint: database

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#31]
Add /database endpoint with support for listing, switching/opening, creating, renaming, deleting databases.

**Comment by cdhorn** [comment]
My thinking is metadata is information about the open/active database/tree and this is somewhat different.

**Comment by DavidMStraub** [comment]
Having an endpoint with *info* about the database is good, but I think we should *not* allow to switch/open/create/rename/delete databases. I think a single API server instance must be tied to a single database instance. In my view those are all tasks that should be done by a server administrator *before* launching the API server.

**Comment by cdhorn** [comment]
Once you have a fully function web front end able to manage as well as present the data in a tree, is not the next logical step to allow the user to manage which tree they are working with? 

In my mind we should try to expose all the functionality of the underlying Gramps code base. That provides the widest range of tools for people who want to experiment with web technologies on top of it to do so.

**Comment by DavidMStraub** [comment]
I disagree. What is the point of having endpoints like `/api/person/handle` when it does not refer to a single database? What happens if somebody with appropriate permissions changes the database while other users are logged in?

I think the whole REST API approach does not make sense if the database is not fixed.

Of course, in principle one could add an additional namespace, like moving everything up one level
`/api/database-id/person/handle/`
but I don't see any benefit to simply running two instances of the app. On the contrary, it will make everything more complicated as many of the settings (e.g. the media base path, ...) would have to be different for different databases. And what would the point/use case be of having the same user database with the same permission levels for multiple family tree databases?

**Comment by cdhorn** [comment]
Hmm, good points. I'm not thinking about multiple users and there it does not make sense. Closing this then.

**Comment by DavidMStraub** [comment]
Actually it would be really cool, some day, to have some kind of Gramps family tree sharing service where users can expose their trees and use them with various apps. But I think this would need an additional management layer on top of our API.

**Comment by Nick-Hall** [comment]
Yes, it had occurred to me that we could consider hosting a web app.

Perhaps the user could select a database when they login?  All future requests would relate to that database.

A database endpoint to list the available databases might be useful.  Creating and deleting databases would be an admin task as previously suggested.

**Comment by cdhorn** [comment]
Yeah you would need to manage things at that layer then. Maybe they pick a tree and you spinup a container or containers for the application instance and if they shared it with other users who want to access it at the same time authenticate and then route them to the active instance. I think with that kind of service you want to allow the user to create and manage their own trees though, I do not see that as an admin task. What if it becomes very popular?

If the plan is to add full create/update/delete support as well which is what I thought isn't multiuser access going to pose some issues anyway? I spent some time looking through stuff and see discussion in the past about how it was never really designed for concurrent use, so you would need some way to serialize write access. A global write lock taken when an editor is opened and released when it is closed or something similar at a minimum probably, no? If that is the case that should probably be a service provided and managed by the API or maybe better yet the core Gramps code and just exposed through the API.

**Comment by cdhorn** [comment]
While that would be a great service, also have to keep in mind GDPR and all the regulations around the handling of personal data.

**Comment by DavidMStraub** [comment]
> If the plan is to add full create/update/delete support as well which is what I thought isn't multiuser access going to pose some issues anyway? I spent some time looking through stuff and see discussion in the past about how it was never really designed for concurrent use, so you would need some way to serialize write access. A global write lock taken when an editor is opened and released when it is closed or something similar at a minimum probably, no? If that is the case that should probably be a service provided and managed by the API or maybe better yet the core Gramps code and just exposed through the API.

See this issue https://github.com/gramps-project/web-api/issues/16

I think it's not going to be a problem, from 5.2 onward, to have concurrent access. But please let's not mix multi-database and multi-user architectures. Let's please focus on building a multi-user, read-write web API for a *single* database.

Technically, using multiple databases is very similar to using multiple API servers since *all* of the configuration has to be different. So I think we are not doing us any favour by complicating the discussion at this stage.

**Comment by Nick-Hall** [comment]
> If the plan is to add full create/update/delete support as well which is what I thought isn't multiuser access going to pose some issues anyway?

Yes.  We should probably create a separate issue for multiuser write access.

It isn't actually very difficult.  I have already created a prototype.

The editor has a copy of the original object so it is easy to create a [JSON Patch](https://en.wikipedia.org/wiki/JSON_Patch) of the changes made.  When the editor is closed the patch can be applied to the object rather writing back the edited version directly.

We would also have to avoid storing the metadata table in memory.  However, this is easy to fix and I'm sure we could get it into the next major release.

**Comment by Nick-Hall** [comment]
> Let's please focus on building a multi-user, read-write web API for a single database.

I agree, but we can bear in mind future requirements when we design the API.
