### ISSUE TITLE
Add paging

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#32]
For collection endpoints that return a list of Gramps objects, we should add the possibility of "paging" to allow clients to lazily load objects in chunks.

I suggest to do this by adding `limit` and `offset` query parameters to `GrampsObjectsResource`.

To make this really useful, we should however also add sorting and it's not entirely clear to me how to do this generically. For instance, what would the query be to return the first 20 people in a list ordered by birth date?

**Comment by Nick-Hall** [comment]
Yes, sorting could be an issue.

We would need to consider the `group_as` and `sort_as` fields when sorting a name.

Also, at the moment there are very few indexes.

**Comment by cdhorn** [comment]
I agree it would be good to be able to handle it in the backend. Maybe sorting should be a separate enhancement though?

**Comment by DavidMStraub** [comment]
It's a separate issue from the point of view of implementation, but from the client/app point of view, I don't think it makes sense to page a collection that is randomly ordered (how would you know on which page to look for an item?).

**Comment by cdhorn** [comment]
Yeah, I guess they do go hand in hand.

Perhaps GrampsObjectsResource should use the get_[object]_handle methods instead of iterating over the handles as they have a sort option on them and then pass the list into filter if there is one to apply.

For your birth date example, is the thinking to allow sorting by date on any event type or just a subset?

**Comment by DavidMStraub** [comment]
Thinking about this a bit more from an app point of view, I think a useful API would be:

```
/api/something/?sort_by=key.subkey.subsubkey&page=1&limit=10`
```

Concretely, for the example given above it would be
```
/api/people/?profile&sort_by=profile.birth.date&page=1&limit=20
```

This would then simply be implemented by sorting the final list in Python, so it wouldn't save time on the server, but that's not the main point (the main point would be that an app doesn't have to download, process, and cache thousands of items when it can only display 20).

(Note that this wouldn't actually sort by date but only by the date string, but it would be equivalent to sorting by the date string in the frontend after fetching all items. "Really" sorting by date would require adding `sortval` to `profile`.)

**Comment by Nick-Hall** [comment]
> Note that this wouldn't actually sort by date but only by the date string

I would expect bug reports if you sort dates by their string representation.

**Comment by DavidMStraub** [comment]
Agreed, but that was not the main point. If we add `sortval` to `profile`, one could do 
```
/api/people/?profile&sort_by=profile.birth.sortval&page=1&limit=20
```

**Comment by cdhorn** [comment]
I wonder if it would make sense to implement sorting as a class of filters in the filters package instead of the API.  Then the functionality would be in the base gramps.gen package. I guess most sorting is handled in the GUI component today.

I guess to do that you would want to pass the instantiated objects around and not the list of handles, and if we had a list of objects returned instead of handles we wouldn't need to instantiate them again either.

**Comment by cdhorn** [comment]
@DavidMStraub I realized for the sort/paging support I added I'm just returning the result set as a list as we have been.  But for the application it really needs to know a little more about the result set, like you return in the search response.  So I have in mind to structure the response like this perhaps:
```
{"data": [],
"metadata": {
    "item_total": int,
    "page_number": int,
    "page_size": int,
    "page_total": int
}
```
This raises some questions.

1. By default I was returning the full result set, and still think we should do so unless asked to do otherwise. I notice the search endpoint requires a page and page size though. How important is consistency here?

2. If a page was requested I defaulted to 20 for size unless specified, not 10. Do you mind if I change search to do same?  Should we make that an option in the configuration file?

3. Do you mind if the search response is refactored into the same format / keywords for consistency?

4. Should the responses from collection endpoints for things other than the major Gramps objects and search also conform to the same format keeping in mind some return lists and some return dictionaries?

**Comment by cdhorn** [comment]
Also should I submit a PR for what I have now and then this would be implemented in a second phase or should I address it now?

**Comment by cdhorn** [comment]
Also I noticed in the search response isn't including offset superflous as I would expect results.total to be 0?

**Comment by DavidMStraub** [comment]
Concerning the respons structuree: good question. It would indeed be a huge change and somehow I would like to keep the object endpoints being lists. Actually I think the page number and page size are not needed in the output as they are part of the arguments. The only non-trivial information that an app would need is the total number of items (the total page number is also a derived quantity). 

There is some [discussion on StackOverflow](https://stackoverflow.com/questions/3715981/what-s-the-best-restful-method-to-return-total-number-of-items-in-an-object) and I really like the idea of using HTTP response headers. What do you think? (Of course the search endpoint would then also have to be changed accordingly.)

Concerning the other questions:

> By default I was returning the full result set, and still think we should do so unless asked to do otherwise. I notice the search endpoint requires a page and page size though. How important is consistency here?

I don't see it as a problem. Also from an application point of view, I see use cases for fetching all objects, but not really for fetching infinitely many search results.

>  If a page was requested I defaulted to 20 for size unless specified, not 10. Do you mind if I change search to do same? Should we make that an option in the configuration file?

No problem, I just took the `whoosh` default but don't have an opinion. I think making it configurable is overkill though, given we have an explicit query argument for it. (So I would expect every application to set that explicitly anyway.)

>  Do you mind if the search response is refactored into the same format / keywords for consistency?

Right, let's make that consistent.

**Comment by cdhorn** [comment]
> There is some discussion on StackOverflow and I really like the idea of using HTTP response headers. What do you think?

Wow, that is a really good idea!  I think X-Total-Count keeps it simple enough, the client knows it sent a page request so will know it can check the header. Agree?

**Comment by cdhorn** [comment]
> > Do you mind if the search response is refactored into the same format / keywords for consistency?
> Right, let's make that consistent.

Actually with the header not needed, so I will just tweak the default to 20

**Comment by cdhorn** [comment]
I don't think we want to remove the info as you have the runtime in there so I figured leave it as is now.

**Comment by DavidMStraub** [comment]
Yeah ... to be honest the runtime isn't that useful anyway. I put it in as it came for free, but in practice the time it takes to look up the handles in the index (which is the runtime) will be much smaller than the time it takes to deserialize the objects...

**Comment by cdhorn** [comment]
So just remove info and return the hits as a list then with the total in the header as well?

**Comment by DavidMStraub** [comment]
I think so, yes.
