### ISSUE TITLE
Add pylint to CI pipeline

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/web-api#58]
... but fix all pylint issues before, or change the pylint conf file accordingly.

**Comment by Nick-Hall** [comment]
I generally recommend using pylint for guidance only.  New files should easily be able to achieve a score of 9.0 or greater.

Sometimes it is sensible to break the rules, and in these cases I prefer to see the messages rather than disabling them in-line.

Having said that, we still may wish to tweak the confoguration file.

**Comment by DavidMStraub** [comment]
Yes, good points. Maybe this is not needed.
