### ISSUE TITLE
Add /api/tools endpoint

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#68]
Expose the tools plugin API.

**Comment by DavidMStraub** [comment]
Here we should carefully consider which of them we want to expose. For the ones that do bulk edits of the database (like changing Gramps IDs) my feeling is that these are things that should not be done on a running server. Since this is a multi-user environment, I think we should only allow operations changing the database that are limited in scope, like adding or modifying a single Gramps object.

**Comment by cdhorn** [comment]
I partially agree, but have you considered a use case other than the one you have in mind?

I do not know enough to do so, but what if someone wanted to develop an Electron based front end as an alternate to the GTK based Gramps one with no intent of ever using it in a multi-user scenario?  Remember exposing the functionality does not mean the API consumer needs to allow use of it in their application.

For that sort of use case you would want to leverage the full Gramps code base as much as possible. So you would want to be able to manage and switch trees with the API, import data to create new ones, and have as many other tools available as possible.

**Comment by cdhorn** [comment]
Looking closer at this I agree @DavidMStraub it may not make sense to expose a lot of these. Or at least if we do someday it is low priority, more useful things to work on.

**Comment by cdhorn** [comment]
Close for now, can revisit someday if makes sense.
