### ISSUE TITLE
Add /api/exporters

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#77]
Related to discussion in PR #59

**Comment by DavidMStraub** [comment]
I closed #59 because I realized it didn't make sense to call the plugin's function manually. I think the API should be, as discussed in #59:

- `/api/exporters`: list of exporters
- `/api/exporters/someformat`: download file in given format.

I think there is no need to have a separate endpoint for options because, as far as I can see, there are no options except the format (correct me if I'm wrong).

For the code, I think we can use this block from https://github.com/gramps-project/gramps/blob/master/gramps/cli/arghandler.py#L592-L596 and the rest can be analogous to reports (#72).

**Comment by cdhorn** [comment]
There are some options in a sort of round about sense, they're mostly handled in gramps.gui.plug.export._exportoptions in the WriterOptionBox class and consist of the construction of a set of filters to be applied. Some predefined to choose from with the option of adding your own custom ones of course.

I think we would want to provide similar functionality and while we can not use that directly it provides a framework for how to go about it. Since the report stuff seems to be wrapped up, at least the initial implementation, I'll take a stab at this one next.
