### ISSUE TITLE
Add version to base url path

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/web-api#90]
I'd like to propose adding a version to the base path for the API, so this initial release would be /api/v1/

While it might never be used, having the option to provide different version in the future if the existing one can not be extended as needed may prove beneficial. I'm not sure what anyones thoughts are on this.

**Comment by Nick-Hall** [comment]
Good idea.  It may prove useful in the future.

**Comment by DavidMStraub** [comment]
I realize I haven't commented on this ... mostly because I don't have a strong opinion. I have the feeling that this is a useful feature for public APIs that exist as a single instance - say, the Github API. For self-hosted APIs, I find it less relevant; but since it doesn't hurt, I'm not opposed to it. Maybe we could also just make the prefix (currently `/api`) configurable (and set its default to `/api/v1`, for instance).

**Comment by DavidMStraub** [comment]
We could additionally add a version number (with minor version) to the metadata endpoint.

**Comment by cdhorn** [comment]
> We could additionally add a version number (with minor version) to the metadata endpoint.

I already added that in addition to the version of Gramps being used. 

You know thinking about it more that is a good distinction, it may be unnecessary. It is more likely that any breaking type changes would simply be managed through the installed version.  And if a 2.0 was ever necessary that coexisted with the current one for a period of time you could break the new one out then.

**Comment by DavidMStraub** [comment]
> You know thinking about it more that is a good distinction, it may be unnecessary. It is more likely that any breaking type changes would simply be managed through the installed version. And if a 2.0 was ever necessary that coexisted with the current one for a period of time you could break the new one out then.

Yes, I think that makes a lot of sense.

**Comment by cdhorn** [comment]
Closing based on our discussion.
